/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/comment/': RouteRecordInfo<'/comment/', '/comment', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/0811': RouteRecordInfo<'/posts/0811', '/posts/0811', Record<never, never>, Record<never, never>>,
    '/posts/2021-sumup': RouteRecordInfo<'/posts/2021-sumup', '/posts/2021-sumup', Record<never, never>, Record<never, never>>,
    '/posts/2022-sumup': RouteRecordInfo<'/posts/2022-sumup', '/posts/2022-sumup', Record<never, never>, Record<never, never>>,
    '/posts/202308notes': RouteRecordInfo<'/posts/202308notes', '/posts/202308notes', Record<never, never>, Record<never, never>>,
    '/posts/20231125': RouteRecordInfo<'/posts/20231125', '/posts/20231125', Record<never, never>, Record<never, never>>,
    '/posts/618recommend': RouteRecordInfo<'/posts/618recommend', '/posts/618recommend', Record<never, never>, Record<never, never>>,
    '/posts/api': RouteRecordInfo<'/posts/api', '/posts/api', Record<never, never>, Record<never, never>>,
    '/posts/gitknow': RouteRecordInfo<'/posts/gitknow', '/posts/gitknow', Record<never, never>, Record<never, never>>,
    '/posts/hello-world': RouteRecordInfo<'/posts/hello-world', '/posts/hello-world', Record<never, never>, Record<never, never>>,
    '/posts/longTime': RouteRecordInfo<'/posts/longTime', '/posts/longTime', Record<never, never>, Record<never, never>>,
    '/posts/musiccase': RouteRecordInfo<'/posts/musiccase', '/posts/musiccase', Record<never, never>, Record<never, never>>,
    '/posts/netfriend': RouteRecordInfo<'/posts/netfriend', '/posts/netfriend', Record<never, never>, Record<never, never>>,
    '/posts/nodetest': RouteRecordInfo<'/posts/nodetest', '/posts/nodetest', Record<never, never>, Record<never, never>>,
    '/posts/oldStory': RouteRecordInfo<'/posts/oldStory', '/posts/oldStory', Record<never, never>, Record<never, never>>,
    '/posts/teamspeak': RouteRecordInfo<'/posts/teamspeak', '/posts/teamspeak', Record<never, never>, Record<never, never>>,
    '/posts/vuetest': RouteRecordInfo<'/posts/vuetest', '/posts/vuetest', Record<never, never>, Record<never, never>>,
    '/posts/wall': RouteRecordInfo<'/posts/wall', '/posts/wall', Record<never, never>, Record<never, never>>,
    '/posts/webpack-optimize': RouteRecordInfo<'/posts/webpack-optimize', '/posts/webpack-optimize', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
